/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.domain;


import java.io.Serializable;

import javax.annotation.Generated;

import com.mymock.webproxy.repository.HasIdField;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wpheader implements Serializable, HasIdField {

	private static final long serialVersionUID = 857227191;

	private Integer id;
	private Integer urlId;
	private String  headerName;
	private String  headerValue;

	public Wpheader() {}

	public Wpheader(Wpheader value) {
		this.id = value.id;
		this.urlId = value.urlId;
		this.headerName = value.headerName;
		this.headerValue = value.headerValue;
	}

	public Wpheader(
		Integer id,
		Integer urlId,
		String  headerName,
		String  headerValue
	) {
		this.id = id;
		this.urlId = urlId;
		this.headerName = headerName;
		this.headerValue = headerValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(Integer urlId) {
		this.urlId = urlId;
	}

	public String getHeaderName() {
		return this.headerName;
	}

	public void setHeaderName(String headerName) {
		this.headerName = headerName;
	}

	public String getHeaderValue() {
		return this.headerValue;
	}

	public void setHeaderValue(String headerValue) {
		this.headerValue = headerValue;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Wpheader (");

		sb.append(id);
		sb.append(", ").append(urlId);
		sb.append(", ").append(headerName);
		sb.append(", ").append(headerValue);

		sb.append(")");
		return sb.toString();
	}
}
