/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.information_schema;


import com.mymock.webproxy.db.information_schema.tables.Catalogs;
import com.mymock.webproxy.db.information_schema.tables.Collations;
import com.mymock.webproxy.db.information_schema.tables.ColumnPrivileges;
import com.mymock.webproxy.db.information_schema.tables.Columns;
import com.mymock.webproxy.db.information_schema.tables.Constants;
import com.mymock.webproxy.db.information_schema.tables.Constraints;
import com.mymock.webproxy.db.information_schema.tables.CrossReferences;
import com.mymock.webproxy.db.information_schema.tables.Domains;
import com.mymock.webproxy.db.information_schema.tables.FunctionAliases;
import com.mymock.webproxy.db.information_schema.tables.FunctionColumns;
import com.mymock.webproxy.db.information_schema.tables.Help;
import com.mymock.webproxy.db.information_schema.tables.InDoubt;
import com.mymock.webproxy.db.information_schema.tables.Indexes;
import com.mymock.webproxy.db.information_schema.tables.Locks;
import com.mymock.webproxy.db.information_schema.tables.QueryStatistics;
import com.mymock.webproxy.db.information_schema.tables.Rights;
import com.mymock.webproxy.db.information_schema.tables.Roles;
import com.mymock.webproxy.db.information_schema.tables.Schemata;
import com.mymock.webproxy.db.information_schema.tables.Sequences;
import com.mymock.webproxy.db.information_schema.tables.SessionState;
import com.mymock.webproxy.db.information_schema.tables.Sessions;
import com.mymock.webproxy.db.information_schema.tables.Settings;
import com.mymock.webproxy.db.information_schema.tables.TablePrivileges;
import com.mymock.webproxy.db.information_schema.tables.TableTypes;
import com.mymock.webproxy.db.information_schema.tables.Triggers;
import com.mymock.webproxy.db.information_schema.tables.TypeInfo;
import com.mymock.webproxy.db.information_schema.tables.Users;
import com.mymock.webproxy.db.information_schema.tables.Views;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table INFORMATION_SCHEMA.QUERY_STATISTICS
	 */
	public static final QueryStatistics QUERY_STATISTICS = com.mymock.webproxy.db.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

	/**
	 * The table INFORMATION_SCHEMA.SESSION_STATE
	 */
	public static final SessionState SESSION_STATE = com.mymock.webproxy.db.information_schema.tables.SessionState.SESSION_STATE;

	/**
	 * The table INFORMATION_SCHEMA.LOCKS
	 */
	public static final Locks LOCKS = com.mymock.webproxy.db.information_schema.tables.Locks.LOCKS;

	/**
	 * The table INFORMATION_SCHEMA.SESSIONS
	 */
	public static final Sessions SESSIONS = com.mymock.webproxy.db.information_schema.tables.Sessions.SESSIONS;

	/**
	 * The table INFORMATION_SCHEMA.TRIGGERS
	 */
	public static final Triggers TRIGGERS = com.mymock.webproxy.db.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table INFORMATION_SCHEMA.DOMAINS
	 */
	public static final Domains DOMAINS = com.mymock.webproxy.db.information_schema.tables.Domains.DOMAINS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTANTS
	 */
	public static final Constants CONSTANTS = com.mymock.webproxy.db.information_schema.tables.Constants.CONSTANTS;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_COLUMNS
	 */
	public static final FunctionColumns FUNCTION_COLUMNS = com.mymock.webproxy.db.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTRAINTS
	 */
	public static final Constraints CONSTRAINTS = com.mymock.webproxy.db.information_schema.tables.Constraints.CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.CROSS_REFERENCES
	 */
	public static final CrossReferences CROSS_REFERENCES = com.mymock.webproxy.db.information_schema.tables.CrossReferences.CROSS_REFERENCES;

	/**
	 * The table INFORMATION_SCHEMA.IN_DOUBT
	 */
	public static final InDoubt IN_DOUBT = com.mymock.webproxy.db.information_schema.tables.InDoubt.IN_DOUBT;

	/**
	 * The table INFORMATION_SCHEMA.VIEWS
	 */
	public static final Views VIEWS = com.mymock.webproxy.db.information_schema.tables.Views.VIEWS;

	/**
	 * The table INFORMATION_SCHEMA.COLLATIONS
	 */
	public static final Collations COLLATIONS = com.mymock.webproxy.db.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table INFORMATION_SCHEMA.COLUMN_PRIVILEGES
	 */
	public static final ColumnPrivileges COLUMN_PRIVILEGES = com.mymock.webproxy.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_PRIVILEGES
	 */
	public static final TablePrivileges TABLE_PRIVILEGES = com.mymock.webproxy.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.SCHEMATA
	 */
	public static final Schemata SCHEMATA = com.mymock.webproxy.db.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_ALIASES
	 */
	public static final FunctionAliases FUNCTION_ALIASES = com.mymock.webproxy.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

	/**
	 * The table INFORMATION_SCHEMA.RIGHTS
	 */
	public static final Rights RIGHTS = com.mymock.webproxy.db.information_schema.tables.Rights.RIGHTS;

	/**
	 * The table INFORMATION_SCHEMA.ROLES
	 */
	public static final Roles ROLES = com.mymock.webproxy.db.information_schema.tables.Roles.ROLES;

	/**
	 * The table INFORMATION_SCHEMA.USERS
	 */
	public static final Users USERS = com.mymock.webproxy.db.information_schema.tables.Users.USERS;

	/**
	 * The table INFORMATION_SCHEMA.SEQUENCES
	 */
	public static final Sequences SEQUENCES = com.mymock.webproxy.db.information_schema.tables.Sequences.SEQUENCES;

	/**
	 * The table INFORMATION_SCHEMA.HELP
	 */
	public static final Help HELP = com.mymock.webproxy.db.information_schema.tables.Help.HELP;

	/**
	 * The table INFORMATION_SCHEMA.SETTINGS
	 */
	public static final Settings SETTINGS = com.mymock.webproxy.db.information_schema.tables.Settings.SETTINGS;

	/**
	 * The table INFORMATION_SCHEMA.CATALOGS
	 */
	public static final Catalogs CATALOGS = com.mymock.webproxy.db.information_schema.tables.Catalogs.CATALOGS;

	/**
	 * The table INFORMATION_SCHEMA.TYPE_INFO
	 */
	public static final TypeInfo TYPE_INFO = com.mymock.webproxy.db.information_schema.tables.TypeInfo.TYPE_INFO;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_TYPES
	 */
	public static final TableTypes TABLE_TYPES = com.mymock.webproxy.db.information_schema.tables.TableTypes.TABLE_TYPES;

	/**
	 * The table INFORMATION_SCHEMA.INDEXES
	 */
	public static final Indexes INDEXES = com.mymock.webproxy.db.information_schema.tables.Indexes.INDEXES;

	/**
	 * The table INFORMATION_SCHEMA.COLUMNS
	 */
	public static final Columns COLUMNS = com.mymock.webproxy.db.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.TABLES
	 */
	public static final com.mymock.webproxy.db.information_schema.tables.Tables TABLES = com.mymock.webproxy.db.information_schema.tables.Tables.TABLES;
}
