/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Url implements Serializable {

	private static final long serialVersionUID = -1774785032;

	private Integer   id;
	private String    address;
	private Timestamp ts;
	private Integer   num;

	public Url() {}

	public Url(Url value) {
		this.id = value.id;
		this.address = value.address;
		this.ts = value.ts;
		this.num = value.num;
	}

	public Url(
		Integer   id,
		String    address,
		Timestamp ts,
		Integer   num
	) {
		this.id = id;
		this.address = address;
		this.ts = ts;
		this.num = num;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Timestamp getTs() {
		return this.ts;
	}

	public void setTs(Timestamp ts) {
		this.ts = ts;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Url (");

		sb.append(id);
		sb.append(", ").append(address);
		sb.append(", ").append(ts);
		sb.append(", ").append(num);

		sb.append(")");
		return sb.toString();
	}
}
