/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.sys.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.sys.Sys;
import org.jooq.example.gradle.db.sys.tables.records.WaitsByHostByLatencyRecord;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaitsByHostByLatency extends TableImpl<WaitsByHostByLatencyRecord> {

	private static final long serialVersionUID = -674889511;

	/**
	 * The reference instance of <code>sys.waits_by_host_by_latency</code>
	 */
	public static final WaitsByHostByLatency WAITS_BY_HOST_BY_LATENCY = new WaitsByHostByLatency();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WaitsByHostByLatencyRecord> getRecordType() {
		return WaitsByHostByLatencyRecord.class;
	}

	/**
	 * The column <code>sys.waits_by_host_by_latency.host</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, String> HOST = createField("host", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>sys.waits_by_host_by_latency.event</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, String> EVENT = createField("event", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>sys.waits_by_host_by_latency.total</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, ULong> TOTAL = createField("total", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.waits_by_host_by_latency.total_latency</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, String> TOTAL_LATENCY = createField("total_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.waits_by_host_by_latency.avg_latency</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, String> AVG_LATENCY = createField("avg_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.waits_by_host_by_latency.max_latency</code>.
	 */
	public final TableField<WaitsByHostByLatencyRecord, String> MAX_LATENCY = createField("max_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>sys.waits_by_host_by_latency</code> table reference
	 */
	public WaitsByHostByLatency() {
		this("waits_by_host_by_latency", null);
	}

	/**
	 * Create an aliased <code>sys.waits_by_host_by_latency</code> table reference
	 */
	public WaitsByHostByLatency(String alias) {
		this(alias, WAITS_BY_HOST_BY_LATENCY);
	}

	private WaitsByHostByLatency(String alias, Table<WaitsByHostByLatencyRecord> aliased) {
		this(alias, aliased, null);
	}

	private WaitsByHostByLatency(String alias, Table<WaitsByHostByLatencyRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WaitsByHostByLatency as(String alias) {
		return new WaitsByHostByLatency(alias, this);
	}

	/**
	 * Rename this table
	 */
	public WaitsByHostByLatency rename(String name) {
		return new WaitsByHostByLatency(name, null);
	}
}
