/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.sys.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.sys.Sys;
import org.jooq.example.gradle.db.sys.tables.records.X$hostSummaryByStagesRecord;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class X$hostSummaryByStages extends TableImpl<X$hostSummaryByStagesRecord> {

	private static final long serialVersionUID = -102092625;

	/**
	 * The reference instance of <code>sys.x$host_summary_by_stages</code>
	 */
	public static final X$hostSummaryByStages X$HOST_SUMMARY_BY_STAGES = new X$hostSummaryByStages();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<X$hostSummaryByStagesRecord> getRecordType() {
		return X$hostSummaryByStagesRecord.class;
	}

	/**
	 * The column <code>sys.x$host_summary_by_stages.host</code>.
	 */
	public final TableField<X$hostSummaryByStagesRecord, String> HOST = createField("host", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>sys.x$host_summary_by_stages.event_name</code>.
	 */
	public final TableField<X$hostSummaryByStagesRecord, String> EVENT_NAME = createField("event_name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>sys.x$host_summary_by_stages.total</code>.
	 */
	public final TableField<X$hostSummaryByStagesRecord, ULong> TOTAL = createField("total", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.x$host_summary_by_stages.total_latency</code>.
	 */
	public final TableField<X$hostSummaryByStagesRecord, ULong> TOTAL_LATENCY = createField("total_latency", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.x$host_summary_by_stages.avg_latency</code>.
	 */
	public final TableField<X$hostSummaryByStagesRecord, ULong> AVG_LATENCY = createField("avg_latency", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * Create a <code>sys.x$host_summary_by_stages</code> table reference
	 */
	public X$hostSummaryByStages() {
		this("x$host_summary_by_stages", null);
	}

	/**
	 * Create an aliased <code>sys.x$host_summary_by_stages</code> table reference
	 */
	public X$hostSummaryByStages(String alias) {
		this(alias, X$HOST_SUMMARY_BY_STAGES);
	}

	private X$hostSummaryByStages(String alias, Table<X$hostSummaryByStagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private X$hostSummaryByStages(String alias, Table<X$hostSummaryByStagesRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public X$hostSummaryByStages as(String alias) {
		return new X$hostSummaryByStages(alias, this);
	}

	/**
	 * Rename this table
	 */
	public X$hostSummaryByStages rename(String name) {
		return new X$hostSummaryByStages(name, null);
	}
}
