/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_.tables;


import com.mymock.webproxy.db.public_.Keys;
import com.mymock.webproxy.db.public_.Public;
import com.mymock.webproxy.db.public_.tables.records.UrlRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Url extends TableImpl<UrlRecord> {

	private static final long serialVersionUID = 26363511;

	/**
	 * The reference instance of <code>PUBLIC.URL</code>
	 */
	public static final Url URL = new Url();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UrlRecord> getRecordType() {
		return UrlRecord.class;
	}

	/**
	 * The column <code>PUBLIC.URL.ID</code>.
	 */
	public final TableField<UrlRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.URL.ADDRESS</code>.
	 */
	public final TableField<UrlRecord, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.CHAR.length(2147483647).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.URL.TS</code>.
	 */
	public final TableField<UrlRecord, Timestamp> TS = createField("TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.URL.NUM</code>.
	 */
	public final TableField<UrlRecord, Integer> NUM = createField("NUM", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.URL</code> table reference
	 */
	public Url() {
		this("URL", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.URL</code> table reference
	 */
	public Url(String alias) {
		this(alias, URL);
	}

	private Url(String alias, Table<UrlRecord> aliased) {
		this(alias, aliased, null);
	}

	private Url(String alias, Table<UrlRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<UrlRecord, Integer> getIdentity() {
		return Keys.IDENTITY_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UrlRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UrlRecord>> getKeys() {
		return Arrays.<UniqueKey<UrlRecord>>asList(Keys.CONSTRAINT_1, Keys.UNIQUE_URL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Url as(String alias) {
		return new Url(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Url rename(String name) {
		return new Url(name, null);
	}
}
