/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_.tables;


import com.mymock.webproxy.db.public_.Keys;
import com.mymock.webproxy.db.public_.Public;
import com.mymock.webproxy.db.public_.tables.records.WpurlRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wpurl extends TableImpl<WpurlRecord> {

	private static final long serialVersionUID = 903000121;

	/**
	 * The reference instance of <code>PUBLIC.WPURL</code>
	 */
	public static final Wpurl WPURL = new Wpurl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WpurlRecord> getRecordType() {
		return WpurlRecord.class;
	}

	/**
	 * The column <code>PUBLIC.WPURL.ID</code>.
	 */
	public final TableField<WpurlRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.WPURL.ADDRESS</code>.
	 */
	public final TableField<WpurlRecord, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.CHAR.length(2147483647).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WPURL.TS</code>.
	 */
	public final TableField<WpurlRecord, Timestamp> TS = createField("TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.WPURL.CNT</code>.
	 */
	public final TableField<WpurlRecord, Integer> CNT = createField("CNT", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.WPURL.CONTENT</code>.
	 */
	public final TableField<WpurlRecord, byte[]> CONTENT = createField("CONTENT", org.jooq.impl.SQLDataType.VARBINARY.defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.WPURL</code> table reference
	 */
	public Wpurl() {
		this("WPURL", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.WPURL</code> table reference
	 */
	public Wpurl(String alias) {
		this(alias, WPURL);
	}

	private Wpurl(String alias, Table<WpurlRecord> aliased) {
		this(alias, aliased, null);
	}

	private Wpurl(String alias, Table<WpurlRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<WpurlRecord, Integer> getIdentity() {
		return Keys.IDENTITY_WPURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WpurlRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WpurlRecord>> getKeys() {
		return Arrays.<UniqueKey<WpurlRecord>>asList(Keys.CONSTRAINT_4, Keys.UNIQUE_URL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Wpurl as(String alias) {
		return new Wpurl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Wpurl rename(String name) {
		return new Wpurl(name, null);
	}
}
