/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.mysql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.example.gradle.db.mysql.tables.ColumnsPriv;
import org.jooq.example.gradle.db.mysql.tables.Db;
import org.jooq.example.gradle.db.mysql.tables.EngineCost;
import org.jooq.example.gradle.db.mysql.tables.Event;
import org.jooq.example.gradle.db.mysql.tables.Func;
import org.jooq.example.gradle.db.mysql.tables.GeneralLog;
import org.jooq.example.gradle.db.mysql.tables.GtidExecuted;
import org.jooq.example.gradle.db.mysql.tables.HelpCategory;
import org.jooq.example.gradle.db.mysql.tables.HelpKeyword;
import org.jooq.example.gradle.db.mysql.tables.HelpRelation;
import org.jooq.example.gradle.db.mysql.tables.HelpTopic;
import org.jooq.example.gradle.db.mysql.tables.InnodbIndexStats;
import org.jooq.example.gradle.db.mysql.tables.InnodbTableStats;
import org.jooq.example.gradle.db.mysql.tables.NdbBinlogIndex;
import org.jooq.example.gradle.db.mysql.tables.Plugin;
import org.jooq.example.gradle.db.mysql.tables.Proc;
import org.jooq.example.gradle.db.mysql.tables.ProcsPriv;
import org.jooq.example.gradle.db.mysql.tables.ProxiesPriv;
import org.jooq.example.gradle.db.mysql.tables.ServerCost;
import org.jooq.example.gradle.db.mysql.tables.Servers;
import org.jooq.example.gradle.db.mysql.tables.SlaveMasterInfo;
import org.jooq.example.gradle.db.mysql.tables.SlaveRelayLogInfo;
import org.jooq.example.gradle.db.mysql.tables.SlaveWorkerInfo;
import org.jooq.example.gradle.db.mysql.tables.SlowLog;
import org.jooq.example.gradle.db.mysql.tables.TablesPriv;
import org.jooq.example.gradle.db.mysql.tables.TimeZone;
import org.jooq.example.gradle.db.mysql.tables.TimeZoneLeapSecond;
import org.jooq.example.gradle.db.mysql.tables.TimeZoneName;
import org.jooq.example.gradle.db.mysql.tables.TimeZoneTransition;
import org.jooq.example.gradle.db.mysql.tables.TimeZoneTransitionType;
import org.jooq.example.gradle.db.mysql.tables.User;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mysql extends SchemaImpl {

	private static final long serialVersionUID = -1585199348;

	/**
	 * The reference instance of <code>mysql</code>
	 */
	public static final Mysql MYSQL = new Mysql();

	/**
	 * No further instances allowed
	 */
	private Mysql() {
		super("mysql");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ColumnsPriv.COLUMNS_PRIV,
			Db.DB,
			EngineCost.ENGINE_COST,
			Event.EVENT,
			Func.FUNC,
			GeneralLog.GENERAL_LOG,
			GtidExecuted.GTID_EXECUTED,
			HelpCategory.HELP_CATEGORY,
			HelpKeyword.HELP_KEYWORD,
			HelpRelation.HELP_RELATION,
			HelpTopic.HELP_TOPIC,
			InnodbIndexStats.INNODB_INDEX_STATS,
			InnodbTableStats.INNODB_TABLE_STATS,
			NdbBinlogIndex.NDB_BINLOG_INDEX,
			Plugin.PLUGIN,
			Proc.PROC,
			ProcsPriv.PROCS_PRIV,
			ProxiesPriv.PROXIES_PRIV,
			Servers.SERVERS,
			ServerCost.SERVER_COST,
			SlaveMasterInfo.SLAVE_MASTER_INFO,
			SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO,
			SlaveWorkerInfo.SLAVE_WORKER_INFO,
			SlowLog.SLOW_LOG,
			TablesPriv.TABLES_PRIV,
			TimeZone.TIME_ZONE,
			TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND,
			TimeZoneName.TIME_ZONE_NAME,
			TimeZoneTransition.TIME_ZONE_TRANSITION,
			TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE,
			User.USER);
	}
}
