/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.sys;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.sys.tables.HostSummary;
import org.jooq.example.gradle.db.sys.tables.HostSummaryByFileIo;
import org.jooq.example.gradle.db.sys.tables.HostSummaryByFileIoType;
import org.jooq.example.gradle.db.sys.tables.HostSummaryByStages;
import org.jooq.example.gradle.db.sys.tables.HostSummaryByStatementLatency;
import org.jooq.example.gradle.db.sys.tables.HostSummaryByStatementType;
import org.jooq.example.gradle.db.sys.tables.InnodbBufferStatsBySchema;
import org.jooq.example.gradle.db.sys.tables.InnodbBufferStatsByTable;
import org.jooq.example.gradle.db.sys.tables.InnodbLockWaits;
import org.jooq.example.gradle.db.sys.tables.IoByThreadByLatency;
import org.jooq.example.gradle.db.sys.tables.IoGlobalByFileByBytes;
import org.jooq.example.gradle.db.sys.tables.IoGlobalByFileByLatency;
import org.jooq.example.gradle.db.sys.tables.IoGlobalByWaitByBytes;
import org.jooq.example.gradle.db.sys.tables.IoGlobalByWaitByLatency;
import org.jooq.example.gradle.db.sys.tables.LatestFileIo;
import org.jooq.example.gradle.db.sys.tables.MemoryByHostByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.MemoryByThreadByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.MemoryByUserByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.MemoryGlobalByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.MemoryGlobalTotal;
import org.jooq.example.gradle.db.sys.tables.Metrics;
import org.jooq.example.gradle.db.sys.tables.Processlist;
import org.jooq.example.gradle.db.sys.tables.PsCheckLostInstrumentation;
import org.jooq.example.gradle.db.sys.tables.SchemaAutoIncrementColumns;
import org.jooq.example.gradle.db.sys.tables.SchemaIndexStatistics;
import org.jooq.example.gradle.db.sys.tables.SchemaObjectOverview;
import org.jooq.example.gradle.db.sys.tables.SchemaRedundantIndexes;
import org.jooq.example.gradle.db.sys.tables.SchemaTableLockWaits;
import org.jooq.example.gradle.db.sys.tables.SchemaTableStatistics;
import org.jooq.example.gradle.db.sys.tables.SchemaTableStatisticsWithBuffer;
import org.jooq.example.gradle.db.sys.tables.SchemaTablesWithFullTableScans;
import org.jooq.example.gradle.db.sys.tables.SchemaUnusedIndexes;
import org.jooq.example.gradle.db.sys.tables.Session;
import org.jooq.example.gradle.db.sys.tables.SessionSslStatus;
import org.jooq.example.gradle.db.sys.tables.StatementAnalysis;
import org.jooq.example.gradle.db.sys.tables.StatementsWithErrorsOrWarnings;
import org.jooq.example.gradle.db.sys.tables.StatementsWithFullTableScans;
import org.jooq.example.gradle.db.sys.tables.StatementsWithRuntimesIn_95thPercentile;
import org.jooq.example.gradle.db.sys.tables.StatementsWithSorting;
import org.jooq.example.gradle.db.sys.tables.StatementsWithTempTables;
import org.jooq.example.gradle.db.sys.tables.SysConfig;
import org.jooq.example.gradle.db.sys.tables.UserSummary;
import org.jooq.example.gradle.db.sys.tables.UserSummaryByFileIo;
import org.jooq.example.gradle.db.sys.tables.UserSummaryByFileIoType;
import org.jooq.example.gradle.db.sys.tables.UserSummaryByStages;
import org.jooq.example.gradle.db.sys.tables.UserSummaryByStatementLatency;
import org.jooq.example.gradle.db.sys.tables.UserSummaryByStatementType;
import org.jooq.example.gradle.db.sys.tables.Version;
import org.jooq.example.gradle.db.sys.tables.WaitClassesGlobalByAvgLatency;
import org.jooq.example.gradle.db.sys.tables.WaitClassesGlobalByLatency;
import org.jooq.example.gradle.db.sys.tables.WaitsByHostByLatency;
import org.jooq.example.gradle.db.sys.tables.WaitsByUserByLatency;
import org.jooq.example.gradle.db.sys.tables.WaitsGlobalByLatency;
import org.jooq.example.gradle.db.sys.tables.X$hostSummary;
import org.jooq.example.gradle.db.sys.tables.X$hostSummaryByFileIo;
import org.jooq.example.gradle.db.sys.tables.X$hostSummaryByFileIoType;
import org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStages;
import org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStatementLatency;
import org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStatementType;
import org.jooq.example.gradle.db.sys.tables.X$innodbBufferStatsBySchema;
import org.jooq.example.gradle.db.sys.tables.X$innodbBufferStatsByTable;
import org.jooq.example.gradle.db.sys.tables.X$innodbLockWaits;
import org.jooq.example.gradle.db.sys.tables.X$ioByThreadByLatency;
import org.jooq.example.gradle.db.sys.tables.X$ioGlobalByFileByBytes;
import org.jooq.example.gradle.db.sys.tables.X$ioGlobalByFileByLatency;
import org.jooq.example.gradle.db.sys.tables.X$ioGlobalByWaitByBytes;
import org.jooq.example.gradle.db.sys.tables.X$ioGlobalByWaitByLatency;
import org.jooq.example.gradle.db.sys.tables.X$latestFileIo;
import org.jooq.example.gradle.db.sys.tables.X$memoryByHostByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.X$memoryByThreadByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.X$memoryByUserByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.X$memoryGlobalByCurrentBytes;
import org.jooq.example.gradle.db.sys.tables.X$memoryGlobalTotal;
import org.jooq.example.gradle.db.sys.tables.X$processlist;
import org.jooq.example.gradle.db.sys.tables.X$psDigestAvgLatencyDistribution;
import org.jooq.example.gradle.db.sys.tables.X$psDigest_95thPercentileByAvgUs;
import org.jooq.example.gradle.db.sys.tables.X$psSchemaTableStatisticsIo;
import org.jooq.example.gradle.db.sys.tables.X$schemaFlattenedKeys;
import org.jooq.example.gradle.db.sys.tables.X$schemaIndexStatistics;
import org.jooq.example.gradle.db.sys.tables.X$schemaTableLockWaits;
import org.jooq.example.gradle.db.sys.tables.X$schemaTableStatistics;
import org.jooq.example.gradle.db.sys.tables.X$schemaTableStatisticsWithBuffer;
import org.jooq.example.gradle.db.sys.tables.X$schemaTablesWithFullTableScans;
import org.jooq.example.gradle.db.sys.tables.X$session;
import org.jooq.example.gradle.db.sys.tables.X$statementAnalysis;
import org.jooq.example.gradle.db.sys.tables.X$statementsWithErrorsOrWarnings;
import org.jooq.example.gradle.db.sys.tables.X$statementsWithFullTableScans;
import org.jooq.example.gradle.db.sys.tables.X$statementsWithRuntimesIn_95thPercentile;
import org.jooq.example.gradle.db.sys.tables.X$statementsWithSorting;
import org.jooq.example.gradle.db.sys.tables.X$statementsWithTempTables;
import org.jooq.example.gradle.db.sys.tables.X$userSummary;
import org.jooq.example.gradle.db.sys.tables.X$userSummaryByFileIo;
import org.jooq.example.gradle.db.sys.tables.X$userSummaryByFileIoType;
import org.jooq.example.gradle.db.sys.tables.X$userSummaryByStages;
import org.jooq.example.gradle.db.sys.tables.X$userSummaryByStatementLatency;
import org.jooq.example.gradle.db.sys.tables.X$userSummaryByStatementType;
import org.jooq.example.gradle.db.sys.tables.X$waitClassesGlobalByAvgLatency;
import org.jooq.example.gradle.db.sys.tables.X$waitClassesGlobalByLatency;
import org.jooq.example.gradle.db.sys.tables.X$waitsByHostByLatency;
import org.jooq.example.gradle.db.sys.tables.X$waitsByUserByLatency;
import org.jooq.example.gradle.db.sys.tables.X$waitsGlobalByLatency;


/**
 * Convenience access to all tables in sys
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * VIEW
	 */
	public static final HostSummary HOST_SUMMARY = org.jooq.example.gradle.db.sys.tables.HostSummary.HOST_SUMMARY;

	/**
	 * VIEW
	 */
	public static final HostSummaryByFileIo HOST_SUMMARY_BY_FILE_IO = org.jooq.example.gradle.db.sys.tables.HostSummaryByFileIo.HOST_SUMMARY_BY_FILE_IO;

	/**
	 * VIEW
	 */
	public static final HostSummaryByFileIoType HOST_SUMMARY_BY_FILE_IO_TYPE = org.jooq.example.gradle.db.sys.tables.HostSummaryByFileIoType.HOST_SUMMARY_BY_FILE_IO_TYPE;

	/**
	 * VIEW
	 */
	public static final HostSummaryByStages HOST_SUMMARY_BY_STAGES = org.jooq.example.gradle.db.sys.tables.HostSummaryByStages.HOST_SUMMARY_BY_STAGES;

	/**
	 * VIEW
	 */
	public static final HostSummaryByStatementLatency HOST_SUMMARY_BY_STATEMENT_LATENCY = org.jooq.example.gradle.db.sys.tables.HostSummaryByStatementLatency.HOST_SUMMARY_BY_STATEMENT_LATENCY;

	/**
	 * VIEW
	 */
	public static final HostSummaryByStatementType HOST_SUMMARY_BY_STATEMENT_TYPE = org.jooq.example.gradle.db.sys.tables.HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE;

	/**
	 * VIEW
	 */
	public static final InnodbBufferStatsBySchema INNODB_BUFFER_STATS_BY_SCHEMA = org.jooq.example.gradle.db.sys.tables.InnodbBufferStatsBySchema.INNODB_BUFFER_STATS_BY_SCHEMA;

	/**
	 * VIEW
	 */
	public static final InnodbBufferStatsByTable INNODB_BUFFER_STATS_BY_TABLE = org.jooq.example.gradle.db.sys.tables.InnodbBufferStatsByTable.INNODB_BUFFER_STATS_BY_TABLE;

	/**
	 * VIEW
	 */
	public static final InnodbLockWaits INNODB_LOCK_WAITS = org.jooq.example.gradle.db.sys.tables.InnodbLockWaits.INNODB_LOCK_WAITS;

	/**
	 * VIEW
	 */
	public static final IoByThreadByLatency IO_BY_THREAD_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.IoByThreadByLatency.IO_BY_THREAD_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final IoGlobalByFileByBytes IO_GLOBAL_BY_FILE_BY_BYTES = org.jooq.example.gradle.db.sys.tables.IoGlobalByFileByBytes.IO_GLOBAL_BY_FILE_BY_BYTES;

	/**
	 * VIEW
	 */
	public static final IoGlobalByFileByLatency IO_GLOBAL_BY_FILE_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.IoGlobalByFileByLatency.IO_GLOBAL_BY_FILE_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final IoGlobalByWaitByBytes IO_GLOBAL_BY_WAIT_BY_BYTES = org.jooq.example.gradle.db.sys.tables.IoGlobalByWaitByBytes.IO_GLOBAL_BY_WAIT_BY_BYTES;

	/**
	 * VIEW
	 */
	public static final IoGlobalByWaitByLatency IO_GLOBAL_BY_WAIT_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.IoGlobalByWaitByLatency.IO_GLOBAL_BY_WAIT_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final LatestFileIo LATEST_FILE_IO = org.jooq.example.gradle.db.sys.tables.LatestFileIo.LATEST_FILE_IO;

	/**
	 * VIEW
	 */
	public static final MemoryByHostByCurrentBytes MEMORY_BY_HOST_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.MemoryByHostByCurrentBytes.MEMORY_BY_HOST_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final MemoryByThreadByCurrentBytes MEMORY_BY_THREAD_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.MemoryByThreadByCurrentBytes.MEMORY_BY_THREAD_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final MemoryByUserByCurrentBytes MEMORY_BY_USER_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.MemoryByUserByCurrentBytes.MEMORY_BY_USER_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final MemoryGlobalByCurrentBytes MEMORY_GLOBAL_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.MemoryGlobalByCurrentBytes.MEMORY_GLOBAL_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final MemoryGlobalTotal MEMORY_GLOBAL_TOTAL = org.jooq.example.gradle.db.sys.tables.MemoryGlobalTotal.MEMORY_GLOBAL_TOTAL;

	/**
	 * VIEW
	 */
	public static final Metrics METRICS = org.jooq.example.gradle.db.sys.tables.Metrics.METRICS;

	/**
	 * VIEW
	 */
	public static final Processlist PROCESSLIST = org.jooq.example.gradle.db.sys.tables.Processlist.PROCESSLIST;

	/**
	 * VIEW
	 */
	public static final PsCheckLostInstrumentation PS_CHECK_LOST_INSTRUMENTATION = org.jooq.example.gradle.db.sys.tables.PsCheckLostInstrumentation.PS_CHECK_LOST_INSTRUMENTATION;

	/**
	 * VIEW
	 */
	public static final SchemaAutoIncrementColumns SCHEMA_AUTO_INCREMENT_COLUMNS = org.jooq.example.gradle.db.sys.tables.SchemaAutoIncrementColumns.SCHEMA_AUTO_INCREMENT_COLUMNS;

	/**
	 * VIEW
	 */
	public static final SchemaIndexStatistics SCHEMA_INDEX_STATISTICS = org.jooq.example.gradle.db.sys.tables.SchemaIndexStatistics.SCHEMA_INDEX_STATISTICS;

	/**
	 * VIEW
	 */
	public static final SchemaObjectOverview SCHEMA_OBJECT_OVERVIEW = org.jooq.example.gradle.db.sys.tables.SchemaObjectOverview.SCHEMA_OBJECT_OVERVIEW;

	/**
	 * VIEW
	 */
	public static final SchemaRedundantIndexes SCHEMA_REDUNDANT_INDEXES = org.jooq.example.gradle.db.sys.tables.SchemaRedundantIndexes.SCHEMA_REDUNDANT_INDEXES;

	/**
	 * VIEW
	 */
	public static final SchemaTablesWithFullTableScans SCHEMA_TABLES_WITH_FULL_TABLE_SCANS = org.jooq.example.gradle.db.sys.tables.SchemaTablesWithFullTableScans.SCHEMA_TABLES_WITH_FULL_TABLE_SCANS;

	/**
	 * VIEW
	 */
	public static final SchemaTableLockWaits SCHEMA_TABLE_LOCK_WAITS = org.jooq.example.gradle.db.sys.tables.SchemaTableLockWaits.SCHEMA_TABLE_LOCK_WAITS;

	/**
	 * VIEW
	 */
	public static final SchemaTableStatistics SCHEMA_TABLE_STATISTICS = org.jooq.example.gradle.db.sys.tables.SchemaTableStatistics.SCHEMA_TABLE_STATISTICS;

	/**
	 * VIEW
	 */
	public static final SchemaTableStatisticsWithBuffer SCHEMA_TABLE_STATISTICS_WITH_BUFFER = org.jooq.example.gradle.db.sys.tables.SchemaTableStatisticsWithBuffer.SCHEMA_TABLE_STATISTICS_WITH_BUFFER;

	/**
	 * VIEW
	 */
	public static final SchemaUnusedIndexes SCHEMA_UNUSED_INDEXES = org.jooq.example.gradle.db.sys.tables.SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES;

	/**
	 * VIEW
	 */
	public static final Session SESSION = org.jooq.example.gradle.db.sys.tables.Session.SESSION;

	/**
	 * VIEW
	 */
	public static final SessionSslStatus SESSION_SSL_STATUS = org.jooq.example.gradle.db.sys.tables.SessionSslStatus.SESSION_SSL_STATUS;

	/**
	 * VIEW
	 */
	public static final StatementsWithErrorsOrWarnings STATEMENTS_WITH_ERRORS_OR_WARNINGS = org.jooq.example.gradle.db.sys.tables.StatementsWithErrorsOrWarnings.STATEMENTS_WITH_ERRORS_OR_WARNINGS;

	/**
	 * VIEW
	 */
	public static final StatementsWithFullTableScans STATEMENTS_WITH_FULL_TABLE_SCANS = org.jooq.example.gradle.db.sys.tables.StatementsWithFullTableScans.STATEMENTS_WITH_FULL_TABLE_SCANS;

	/**
	 * VIEW
	 */
	public static final StatementsWithRuntimesIn_95thPercentile STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE = org.jooq.example.gradle.db.sys.tables.StatementsWithRuntimesIn_95thPercentile.STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE;

	/**
	 * VIEW
	 */
	public static final StatementsWithSorting STATEMENTS_WITH_SORTING = org.jooq.example.gradle.db.sys.tables.StatementsWithSorting.STATEMENTS_WITH_SORTING;

	/**
	 * VIEW
	 */
	public static final StatementsWithTempTables STATEMENTS_WITH_TEMP_TABLES = org.jooq.example.gradle.db.sys.tables.StatementsWithTempTables.STATEMENTS_WITH_TEMP_TABLES;

	/**
	 * VIEW
	 */
	public static final StatementAnalysis STATEMENT_ANALYSIS = org.jooq.example.gradle.db.sys.tables.StatementAnalysis.STATEMENT_ANALYSIS;

	/**
	 * The table sys.sys_config
	 */
	public static final SysConfig SYS_CONFIG = org.jooq.example.gradle.db.sys.tables.SysConfig.SYS_CONFIG;

	/**
	 * VIEW
	 */
	public static final UserSummary USER_SUMMARY = org.jooq.example.gradle.db.sys.tables.UserSummary.USER_SUMMARY;

	/**
	 * VIEW
	 */
	public static final UserSummaryByFileIo USER_SUMMARY_BY_FILE_IO = org.jooq.example.gradle.db.sys.tables.UserSummaryByFileIo.USER_SUMMARY_BY_FILE_IO;

	/**
	 * VIEW
	 */
	public static final UserSummaryByFileIoType USER_SUMMARY_BY_FILE_IO_TYPE = org.jooq.example.gradle.db.sys.tables.UserSummaryByFileIoType.USER_SUMMARY_BY_FILE_IO_TYPE;

	/**
	 * VIEW
	 */
	public static final UserSummaryByStages USER_SUMMARY_BY_STAGES = org.jooq.example.gradle.db.sys.tables.UserSummaryByStages.USER_SUMMARY_BY_STAGES;

	/**
	 * VIEW
	 */
	public static final UserSummaryByStatementLatency USER_SUMMARY_BY_STATEMENT_LATENCY = org.jooq.example.gradle.db.sys.tables.UserSummaryByStatementLatency.USER_SUMMARY_BY_STATEMENT_LATENCY;

	/**
	 * VIEW
	 */
	public static final UserSummaryByStatementType USER_SUMMARY_BY_STATEMENT_TYPE = org.jooq.example.gradle.db.sys.tables.UserSummaryByStatementType.USER_SUMMARY_BY_STATEMENT_TYPE;

	/**
	 * VIEW
	 */
	public static final Version VERSION = org.jooq.example.gradle.db.sys.tables.Version.VERSION;

	/**
	 * VIEW
	 */
	public static final WaitsByHostByLatency WAITS_BY_HOST_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.WaitsByHostByLatency.WAITS_BY_HOST_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final WaitsByUserByLatency WAITS_BY_USER_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.WaitsByUserByLatency.WAITS_BY_USER_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final WaitsGlobalByLatency WAITS_GLOBAL_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.WaitsGlobalByLatency.WAITS_GLOBAL_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final WaitClassesGlobalByAvgLatency WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY = org.jooq.example.gradle.db.sys.tables.WaitClassesGlobalByAvgLatency.WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY;

	/**
	 * VIEW
	 */
	public static final WaitClassesGlobalByLatency WAIT_CLASSES_GLOBAL_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.WaitClassesGlobalByLatency.WAIT_CLASSES_GLOBAL_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$hostSummary X$HOST_SUMMARY = org.jooq.example.gradle.db.sys.tables.X$hostSummary.X$HOST_SUMMARY;

	/**
	 * VIEW
	 */
	public static final X$hostSummaryByFileIo X$HOST_SUMMARY_BY_FILE_IO = org.jooq.example.gradle.db.sys.tables.X$hostSummaryByFileIo.X$HOST_SUMMARY_BY_FILE_IO;

	/**
	 * VIEW
	 */
	public static final X$hostSummaryByFileIoType X$HOST_SUMMARY_BY_FILE_IO_TYPE = org.jooq.example.gradle.db.sys.tables.X$hostSummaryByFileIoType.X$HOST_SUMMARY_BY_FILE_IO_TYPE;

	/**
	 * VIEW
	 */
	public static final X$hostSummaryByStages X$HOST_SUMMARY_BY_STAGES = org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStages.X$HOST_SUMMARY_BY_STAGES;

	/**
	 * VIEW
	 */
	public static final X$hostSummaryByStatementLatency X$HOST_SUMMARY_BY_STATEMENT_LATENCY = org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStatementLatency.X$HOST_SUMMARY_BY_STATEMENT_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$hostSummaryByStatementType X$HOST_SUMMARY_BY_STATEMENT_TYPE = org.jooq.example.gradle.db.sys.tables.X$hostSummaryByStatementType.X$HOST_SUMMARY_BY_STATEMENT_TYPE;

	/**
	 * VIEW
	 */
	public static final X$innodbBufferStatsBySchema X$INNODB_BUFFER_STATS_BY_SCHEMA = org.jooq.example.gradle.db.sys.tables.X$innodbBufferStatsBySchema.X$INNODB_BUFFER_STATS_BY_SCHEMA;

	/**
	 * VIEW
	 */
	public static final X$innodbBufferStatsByTable X$INNODB_BUFFER_STATS_BY_TABLE = org.jooq.example.gradle.db.sys.tables.X$innodbBufferStatsByTable.X$INNODB_BUFFER_STATS_BY_TABLE;

	/**
	 * VIEW
	 */
	public static final X$innodbLockWaits X$INNODB_LOCK_WAITS = org.jooq.example.gradle.db.sys.tables.X$innodbLockWaits.X$INNODB_LOCK_WAITS;

	/**
	 * VIEW
	 */
	public static final X$ioByThreadByLatency X$IO_BY_THREAD_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$ioByThreadByLatency.X$IO_BY_THREAD_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$ioGlobalByFileByBytes X$IO_GLOBAL_BY_FILE_BY_BYTES = org.jooq.example.gradle.db.sys.tables.X$ioGlobalByFileByBytes.X$IO_GLOBAL_BY_FILE_BY_BYTES;

	/**
	 * VIEW
	 */
	public static final X$ioGlobalByFileByLatency X$IO_GLOBAL_BY_FILE_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$ioGlobalByFileByLatency.X$IO_GLOBAL_BY_FILE_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$ioGlobalByWaitByBytes X$IO_GLOBAL_BY_WAIT_BY_BYTES = org.jooq.example.gradle.db.sys.tables.X$ioGlobalByWaitByBytes.X$IO_GLOBAL_BY_WAIT_BY_BYTES;

	/**
	 * VIEW
	 */
	public static final X$ioGlobalByWaitByLatency X$IO_GLOBAL_BY_WAIT_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$ioGlobalByWaitByLatency.X$IO_GLOBAL_BY_WAIT_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$latestFileIo X$LATEST_FILE_IO = org.jooq.example.gradle.db.sys.tables.X$latestFileIo.X$LATEST_FILE_IO;

	/**
	 * VIEW
	 */
	public static final X$memoryByHostByCurrentBytes X$MEMORY_BY_HOST_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.X$memoryByHostByCurrentBytes.X$MEMORY_BY_HOST_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final X$memoryByThreadByCurrentBytes X$MEMORY_BY_THREAD_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.X$memoryByThreadByCurrentBytes.X$MEMORY_BY_THREAD_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final X$memoryByUserByCurrentBytes X$MEMORY_BY_USER_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.X$memoryByUserByCurrentBytes.X$MEMORY_BY_USER_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final X$memoryGlobalByCurrentBytes X$MEMORY_GLOBAL_BY_CURRENT_BYTES = org.jooq.example.gradle.db.sys.tables.X$memoryGlobalByCurrentBytes.X$MEMORY_GLOBAL_BY_CURRENT_BYTES;

	/**
	 * VIEW
	 */
	public static final X$memoryGlobalTotal X$MEMORY_GLOBAL_TOTAL = org.jooq.example.gradle.db.sys.tables.X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL;

	/**
	 * VIEW
	 */
	public static final X$processlist X$PROCESSLIST = org.jooq.example.gradle.db.sys.tables.X$processlist.X$PROCESSLIST;

	/**
	 * VIEW
	 */
	public static final X$psDigest_95thPercentileByAvgUs X$PS_DIGEST_95TH_PERCENTILE_BY_AVG_US = org.jooq.example.gradle.db.sys.tables.X$psDigest_95thPercentileByAvgUs.X$PS_DIGEST_95TH_PERCENTILE_BY_AVG_US;

	/**
	 * VIEW
	 */
	public static final X$psDigestAvgLatencyDistribution X$PS_DIGEST_AVG_LATENCY_DISTRIBUTION = org.jooq.example.gradle.db.sys.tables.X$psDigestAvgLatencyDistribution.X$PS_DIGEST_AVG_LATENCY_DISTRIBUTION;

	/**
	 * VIEW
	 */
	public static final X$psSchemaTableStatisticsIo X$PS_SCHEMA_TABLE_STATISTICS_IO = org.jooq.example.gradle.db.sys.tables.X$psSchemaTableStatisticsIo.X$PS_SCHEMA_TABLE_STATISTICS_IO;

	/**
	 * VIEW
	 */
	public static final X$schemaFlattenedKeys X$SCHEMA_FLATTENED_KEYS = org.jooq.example.gradle.db.sys.tables.X$schemaFlattenedKeys.X$SCHEMA_FLATTENED_KEYS;

	/**
	 * VIEW
	 */
	public static final X$schemaIndexStatistics X$SCHEMA_INDEX_STATISTICS = org.jooq.example.gradle.db.sys.tables.X$schemaIndexStatistics.X$SCHEMA_INDEX_STATISTICS;

	/**
	 * VIEW
	 */
	public static final X$schemaTablesWithFullTableScans X$SCHEMA_TABLES_WITH_FULL_TABLE_SCANS = org.jooq.example.gradle.db.sys.tables.X$schemaTablesWithFullTableScans.X$SCHEMA_TABLES_WITH_FULL_TABLE_SCANS;

	/**
	 * VIEW
	 */
	public static final X$schemaTableLockWaits X$SCHEMA_TABLE_LOCK_WAITS = org.jooq.example.gradle.db.sys.tables.X$schemaTableLockWaits.X$SCHEMA_TABLE_LOCK_WAITS;

	/**
	 * VIEW
	 */
	public static final X$schemaTableStatistics X$SCHEMA_TABLE_STATISTICS = org.jooq.example.gradle.db.sys.tables.X$schemaTableStatistics.X$SCHEMA_TABLE_STATISTICS;

	/**
	 * VIEW
	 */
	public static final X$schemaTableStatisticsWithBuffer X$SCHEMA_TABLE_STATISTICS_WITH_BUFFER = org.jooq.example.gradle.db.sys.tables.X$schemaTableStatisticsWithBuffer.X$SCHEMA_TABLE_STATISTICS_WITH_BUFFER;

	/**
	 * VIEW
	 */
	public static final X$session X$SESSION = org.jooq.example.gradle.db.sys.tables.X$session.X$SESSION;

	/**
	 * VIEW
	 */
	public static final X$statementsWithErrorsOrWarnings X$STATEMENTS_WITH_ERRORS_OR_WARNINGS = org.jooq.example.gradle.db.sys.tables.X$statementsWithErrorsOrWarnings.X$STATEMENTS_WITH_ERRORS_OR_WARNINGS;

	/**
	 * VIEW
	 */
	public static final X$statementsWithFullTableScans X$STATEMENTS_WITH_FULL_TABLE_SCANS = org.jooq.example.gradle.db.sys.tables.X$statementsWithFullTableScans.X$STATEMENTS_WITH_FULL_TABLE_SCANS;

	/**
	 * VIEW
	 */
	public static final X$statementsWithRuntimesIn_95thPercentile X$STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE = org.jooq.example.gradle.db.sys.tables.X$statementsWithRuntimesIn_95thPercentile.X$STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE;

	/**
	 * VIEW
	 */
	public static final X$statementsWithSorting X$STATEMENTS_WITH_SORTING = org.jooq.example.gradle.db.sys.tables.X$statementsWithSorting.X$STATEMENTS_WITH_SORTING;

	/**
	 * VIEW
	 */
	public static final X$statementsWithTempTables X$STATEMENTS_WITH_TEMP_TABLES = org.jooq.example.gradle.db.sys.tables.X$statementsWithTempTables.X$STATEMENTS_WITH_TEMP_TABLES;

	/**
	 * VIEW
	 */
	public static final X$statementAnalysis X$STATEMENT_ANALYSIS = org.jooq.example.gradle.db.sys.tables.X$statementAnalysis.X$STATEMENT_ANALYSIS;

	/**
	 * VIEW
	 */
	public static final X$userSummary X$USER_SUMMARY = org.jooq.example.gradle.db.sys.tables.X$userSummary.X$USER_SUMMARY;

	/**
	 * VIEW
	 */
	public static final X$userSummaryByFileIo X$USER_SUMMARY_BY_FILE_IO = org.jooq.example.gradle.db.sys.tables.X$userSummaryByFileIo.X$USER_SUMMARY_BY_FILE_IO;

	/**
	 * VIEW
	 */
	public static final X$userSummaryByFileIoType X$USER_SUMMARY_BY_FILE_IO_TYPE = org.jooq.example.gradle.db.sys.tables.X$userSummaryByFileIoType.X$USER_SUMMARY_BY_FILE_IO_TYPE;

	/**
	 * VIEW
	 */
	public static final X$userSummaryByStages X$USER_SUMMARY_BY_STAGES = org.jooq.example.gradle.db.sys.tables.X$userSummaryByStages.X$USER_SUMMARY_BY_STAGES;

	/**
	 * VIEW
	 */
	public static final X$userSummaryByStatementLatency X$USER_SUMMARY_BY_STATEMENT_LATENCY = org.jooq.example.gradle.db.sys.tables.X$userSummaryByStatementLatency.X$USER_SUMMARY_BY_STATEMENT_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$userSummaryByStatementType X$USER_SUMMARY_BY_STATEMENT_TYPE = org.jooq.example.gradle.db.sys.tables.X$userSummaryByStatementType.X$USER_SUMMARY_BY_STATEMENT_TYPE;

	/**
	 * VIEW
	 */
	public static final X$waitsByHostByLatency X$WAITS_BY_HOST_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$waitsByHostByLatency.X$WAITS_BY_HOST_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$waitsByUserByLatency X$WAITS_BY_USER_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$waitsByUserByLatency.X$WAITS_BY_USER_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$waitsGlobalByLatency X$WAITS_GLOBAL_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$waitsGlobalByLatency.X$WAITS_GLOBAL_BY_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$waitClassesGlobalByAvgLatency X$WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY = org.jooq.example.gradle.db.sys.tables.X$waitClassesGlobalByAvgLatency.X$WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY;

	/**
	 * VIEW
	 */
	public static final X$waitClassesGlobalByLatency X$WAIT_CLASSES_GLOBAL_BY_LATENCY = org.jooq.example.gradle.db.sys.tables.X$waitClassesGlobalByLatency.X$WAIT_CLASSES_GLOBAL_BY_LATENCY;
}
