/**
 * This class is generated by jOOQ
 */
package com.mymock.db.information_schema;


import com.mymock.db.information_schema.tables.CharacterSets;
import com.mymock.db.information_schema.tables.CollationCharacterSetApplicability;
import com.mymock.db.information_schema.tables.Collations;
import com.mymock.db.information_schema.tables.ColumnPrivileges;
import com.mymock.db.information_schema.tables.Columns;
import com.mymock.db.information_schema.tables.Engines;
import com.mymock.db.information_schema.tables.Events;
import com.mymock.db.information_schema.tables.Files;
import com.mymock.db.information_schema.tables.GlobalStatus;
import com.mymock.db.information_schema.tables.GlobalVariables;
import com.mymock.db.information_schema.tables.InnodbBufferPage;
import com.mymock.db.information_schema.tables.InnodbBufferPageLru;
import com.mymock.db.information_schema.tables.InnodbBufferPoolStats;
import com.mymock.db.information_schema.tables.InnodbCmp;
import com.mymock.db.information_schema.tables.InnodbCmpPerIndex;
import com.mymock.db.information_schema.tables.InnodbCmpPerIndexReset;
import com.mymock.db.information_schema.tables.InnodbCmpReset;
import com.mymock.db.information_schema.tables.InnodbCmpmem;
import com.mymock.db.information_schema.tables.InnodbCmpmemReset;
import com.mymock.db.information_schema.tables.InnodbFtBeingDeleted;
import com.mymock.db.information_schema.tables.InnodbFtConfig;
import com.mymock.db.information_schema.tables.InnodbFtDefaultStopword;
import com.mymock.db.information_schema.tables.InnodbFtDeleted;
import com.mymock.db.information_schema.tables.InnodbFtIndexCache;
import com.mymock.db.information_schema.tables.InnodbFtIndexTable;
import com.mymock.db.information_schema.tables.InnodbLockWaits;
import com.mymock.db.information_schema.tables.InnodbLocks;
import com.mymock.db.information_schema.tables.InnodbMetrics;
import com.mymock.db.information_schema.tables.InnodbSysColumns;
import com.mymock.db.information_schema.tables.InnodbSysDatafiles;
import com.mymock.db.information_schema.tables.InnodbSysFields;
import com.mymock.db.information_schema.tables.InnodbSysForeign;
import com.mymock.db.information_schema.tables.InnodbSysForeignCols;
import com.mymock.db.information_schema.tables.InnodbSysIndexes;
import com.mymock.db.information_schema.tables.InnodbSysTables;
import com.mymock.db.information_schema.tables.InnodbSysTablespaces;
import com.mymock.db.information_schema.tables.InnodbSysTablestats;
import com.mymock.db.information_schema.tables.InnodbSysVirtual;
import com.mymock.db.information_schema.tables.InnodbTempTableInfo;
import com.mymock.db.information_schema.tables.InnodbTrx;
import com.mymock.db.information_schema.tables.KeyColumnUsage;
import com.mymock.db.information_schema.tables.OptimizerTrace;
import com.mymock.db.information_schema.tables.Parameters;
import com.mymock.db.information_schema.tables.Partitions;
import com.mymock.db.information_schema.tables.Plugins;
import com.mymock.db.information_schema.tables.Processlist;
import com.mymock.db.information_schema.tables.Profiling;
import com.mymock.db.information_schema.tables.ReferentialConstraints;
import com.mymock.db.information_schema.tables.Routines;
import com.mymock.db.information_schema.tables.SchemaPrivileges;
import com.mymock.db.information_schema.tables.Schemata;
import com.mymock.db.information_schema.tables.SessionStatus;
import com.mymock.db.information_schema.tables.SessionVariables;
import com.mymock.db.information_schema.tables.Statistics;
import com.mymock.db.information_schema.tables.TableConstraints;
import com.mymock.db.information_schema.tables.TablePrivileges;
import com.mymock.db.information_schema.tables.Tablespaces;
import com.mymock.db.information_schema.tables.Triggers;
import com.mymock.db.information_schema.tables.UserPrivileges;
import com.mymock.db.information_schema.tables.Views;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in information_schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table information_schema.CHARACTER_SETS
	 */
	public static final CharacterSets CHARACTER_SETS = com.mymock.db.information_schema.tables.CharacterSets.CHARACTER_SETS;

	/**
	 * The table information_schema.COLLATIONS
	 */
	public static final Collations COLLATIONS = com.mymock.db.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table information_schema.COLLATION_CHARACTER_SET_APPLICABILITY
	 */
	public static final CollationCharacterSetApplicability COLLATION_CHARACTER_SET_APPLICABILITY = com.mymock.db.information_schema.tables.CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY;

	/**
	 * The table information_schema.COLUMNS
	 */
	public static final Columns COLUMNS = com.mymock.db.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table information_schema.COLUMN_PRIVILEGES
	 */
	public static final ColumnPrivileges COLUMN_PRIVILEGES = com.mymock.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table information_schema.ENGINES
	 */
	public static final Engines ENGINES = com.mymock.db.information_schema.tables.Engines.ENGINES;

	/**
	 * The table information_schema.EVENTS
	 */
	public static final Events EVENTS = com.mymock.db.information_schema.tables.Events.EVENTS;

	/**
	 * The table information_schema.FILES
	 */
	public static final Files FILES = com.mymock.db.information_schema.tables.Files.FILES;

	/**
	 * The table information_schema.GLOBAL_STATUS
	 */
	public static final GlobalStatus GLOBAL_STATUS = com.mymock.db.information_schema.tables.GlobalStatus.GLOBAL_STATUS;

	/**
	 * The table information_schema.GLOBAL_VARIABLES
	 */
	public static final GlobalVariables GLOBAL_VARIABLES = com.mymock.db.information_schema.tables.GlobalVariables.GLOBAL_VARIABLES;

	/**
	 * The table information_schema.INNODB_BUFFER_PAGE
	 */
	public static final InnodbBufferPage INNODB_BUFFER_PAGE = com.mymock.db.information_schema.tables.InnodbBufferPage.INNODB_BUFFER_PAGE;

	/**
	 * The table information_schema.INNODB_BUFFER_PAGE_LRU
	 */
	public static final InnodbBufferPageLru INNODB_BUFFER_PAGE_LRU = com.mymock.db.information_schema.tables.InnodbBufferPageLru.INNODB_BUFFER_PAGE_LRU;

	/**
	 * The table information_schema.INNODB_BUFFER_POOL_STATS
	 */
	public static final InnodbBufferPoolStats INNODB_BUFFER_POOL_STATS = com.mymock.db.information_schema.tables.InnodbBufferPoolStats.INNODB_BUFFER_POOL_STATS;

	/**
	 * The table information_schema.INNODB_CMP
	 */
	public static final InnodbCmp INNODB_CMP = com.mymock.db.information_schema.tables.InnodbCmp.INNODB_CMP;

	/**
	 * The table information_schema.INNODB_CMPMEM
	 */
	public static final InnodbCmpmem INNODB_CMPMEM = com.mymock.db.information_schema.tables.InnodbCmpmem.INNODB_CMPMEM;

	/**
	 * The table information_schema.INNODB_CMPMEM_RESET
	 */
	public static final InnodbCmpmemReset INNODB_CMPMEM_RESET = com.mymock.db.information_schema.tables.InnodbCmpmemReset.INNODB_CMPMEM_RESET;

	/**
	 * The table information_schema.INNODB_CMP_PER_INDEX
	 */
	public static final InnodbCmpPerIndex INNODB_CMP_PER_INDEX = com.mymock.db.information_schema.tables.InnodbCmpPerIndex.INNODB_CMP_PER_INDEX;

	/**
	 * The table information_schema.INNODB_CMP_PER_INDEX_RESET
	 */
	public static final InnodbCmpPerIndexReset INNODB_CMP_PER_INDEX_RESET = com.mymock.db.information_schema.tables.InnodbCmpPerIndexReset.INNODB_CMP_PER_INDEX_RESET;

	/**
	 * The table information_schema.INNODB_CMP_RESET
	 */
	public static final InnodbCmpReset INNODB_CMP_RESET = com.mymock.db.information_schema.tables.InnodbCmpReset.INNODB_CMP_RESET;

	/**
	 * The table information_schema.INNODB_FT_BEING_DELETED
	 */
	public static final InnodbFtBeingDeleted INNODB_FT_BEING_DELETED = com.mymock.db.information_schema.tables.InnodbFtBeingDeleted.INNODB_FT_BEING_DELETED;

	/**
	 * The table information_schema.INNODB_FT_CONFIG
	 */
	public static final InnodbFtConfig INNODB_FT_CONFIG = com.mymock.db.information_schema.tables.InnodbFtConfig.INNODB_FT_CONFIG;

	/**
	 * The table information_schema.INNODB_FT_DEFAULT_STOPWORD
	 */
	public static final InnodbFtDefaultStopword INNODB_FT_DEFAULT_STOPWORD = com.mymock.db.information_schema.tables.InnodbFtDefaultStopword.INNODB_FT_DEFAULT_STOPWORD;

	/**
	 * The table information_schema.INNODB_FT_DELETED
	 */
	public static final InnodbFtDeleted INNODB_FT_DELETED = com.mymock.db.information_schema.tables.InnodbFtDeleted.INNODB_FT_DELETED;

	/**
	 * The table information_schema.INNODB_FT_INDEX_CACHE
	 */
	public static final InnodbFtIndexCache INNODB_FT_INDEX_CACHE = com.mymock.db.information_schema.tables.InnodbFtIndexCache.INNODB_FT_INDEX_CACHE;

	/**
	 * The table information_schema.INNODB_FT_INDEX_TABLE
	 */
	public static final InnodbFtIndexTable INNODB_FT_INDEX_TABLE = com.mymock.db.information_schema.tables.InnodbFtIndexTable.INNODB_FT_INDEX_TABLE;

	/**
	 * The table information_schema.INNODB_LOCKS
	 */
	public static final InnodbLocks INNODB_LOCKS = com.mymock.db.information_schema.tables.InnodbLocks.INNODB_LOCKS;

	/**
	 * The table information_schema.INNODB_LOCK_WAITS
	 */
	public static final InnodbLockWaits INNODB_LOCK_WAITS = com.mymock.db.information_schema.tables.InnodbLockWaits.INNODB_LOCK_WAITS;

	/**
	 * The table information_schema.INNODB_METRICS
	 */
	public static final InnodbMetrics INNODB_METRICS = com.mymock.db.information_schema.tables.InnodbMetrics.INNODB_METRICS;

	/**
	 * The table information_schema.INNODB_SYS_COLUMNS
	 */
	public static final InnodbSysColumns INNODB_SYS_COLUMNS = com.mymock.db.information_schema.tables.InnodbSysColumns.INNODB_SYS_COLUMNS;

	/**
	 * The table information_schema.INNODB_SYS_DATAFILES
	 */
	public static final InnodbSysDatafiles INNODB_SYS_DATAFILES = com.mymock.db.information_schema.tables.InnodbSysDatafiles.INNODB_SYS_DATAFILES;

	/**
	 * The table information_schema.INNODB_SYS_FIELDS
	 */
	public static final InnodbSysFields INNODB_SYS_FIELDS = com.mymock.db.information_schema.tables.InnodbSysFields.INNODB_SYS_FIELDS;

	/**
	 * The table information_schema.INNODB_SYS_FOREIGN
	 */
	public static final InnodbSysForeign INNODB_SYS_FOREIGN = com.mymock.db.information_schema.tables.InnodbSysForeign.INNODB_SYS_FOREIGN;

	/**
	 * The table information_schema.INNODB_SYS_FOREIGN_COLS
	 */
	public static final InnodbSysForeignCols INNODB_SYS_FOREIGN_COLS = com.mymock.db.information_schema.tables.InnodbSysForeignCols.INNODB_SYS_FOREIGN_COLS;

	/**
	 * The table information_schema.INNODB_SYS_INDEXES
	 */
	public static final InnodbSysIndexes INNODB_SYS_INDEXES = com.mymock.db.information_schema.tables.InnodbSysIndexes.INNODB_SYS_INDEXES;

	/**
	 * The table information_schema.INNODB_SYS_TABLES
	 */
	public static final InnodbSysTables INNODB_SYS_TABLES = com.mymock.db.information_schema.tables.InnodbSysTables.INNODB_SYS_TABLES;

	/**
	 * The table information_schema.INNODB_SYS_TABLESPACES
	 */
	public static final InnodbSysTablespaces INNODB_SYS_TABLESPACES = com.mymock.db.information_schema.tables.InnodbSysTablespaces.INNODB_SYS_TABLESPACES;

	/**
	 * The table information_schema.INNODB_SYS_TABLESTATS
	 */
	public static final InnodbSysTablestats INNODB_SYS_TABLESTATS = com.mymock.db.information_schema.tables.InnodbSysTablestats.INNODB_SYS_TABLESTATS;

	/**
	 * The table information_schema.INNODB_SYS_VIRTUAL
	 */
	public static final InnodbSysVirtual INNODB_SYS_VIRTUAL = com.mymock.db.information_schema.tables.InnodbSysVirtual.INNODB_SYS_VIRTUAL;

	/**
	 * The table information_schema.INNODB_TEMP_TABLE_INFO
	 */
	public static final InnodbTempTableInfo INNODB_TEMP_TABLE_INFO = com.mymock.db.information_schema.tables.InnodbTempTableInfo.INNODB_TEMP_TABLE_INFO;

	/**
	 * The table information_schema.INNODB_TRX
	 */
	public static final InnodbTrx INNODB_TRX = com.mymock.db.information_schema.tables.InnodbTrx.INNODB_TRX;

	/**
	 * The table information_schema.KEY_COLUMN_USAGE
	 */
	public static final KeyColumnUsage KEY_COLUMN_USAGE = com.mymock.db.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

	/**
	 * The table information_schema.OPTIMIZER_TRACE
	 */
	public static final OptimizerTrace OPTIMIZER_TRACE = com.mymock.db.information_schema.tables.OptimizerTrace.OPTIMIZER_TRACE;

	/**
	 * The table information_schema.PARAMETERS
	 */
	public static final Parameters PARAMETERS = com.mymock.db.information_schema.tables.Parameters.PARAMETERS;

	/**
	 * The table information_schema.PARTITIONS
	 */
	public static final Partitions PARTITIONS = com.mymock.db.information_schema.tables.Partitions.PARTITIONS;

	/**
	 * The table information_schema.PLUGINS
	 */
	public static final Plugins PLUGINS = com.mymock.db.information_schema.tables.Plugins.PLUGINS;

	/**
	 * The table information_schema.PROCESSLIST
	 */
	public static final Processlist PROCESSLIST = com.mymock.db.information_schema.tables.Processlist.PROCESSLIST;

	/**
	 * The table information_schema.PROFILING
	 */
	public static final Profiling PROFILING = com.mymock.db.information_schema.tables.Profiling.PROFILING;

	/**
	 * The table information_schema.REFERENTIAL_CONSTRAINTS
	 */
	public static final ReferentialConstraints REFERENTIAL_CONSTRAINTS = com.mymock.db.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

	/**
	 * The table information_schema.ROUTINES
	 */
	public static final Routines ROUTINES = com.mymock.db.information_schema.tables.Routines.ROUTINES;

	/**
	 * The table information_schema.SCHEMATA
	 */
	public static final Schemata SCHEMATA = com.mymock.db.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table information_schema.SCHEMA_PRIVILEGES
	 */
	public static final SchemaPrivileges SCHEMA_PRIVILEGES = com.mymock.db.information_schema.tables.SchemaPrivileges.SCHEMA_PRIVILEGES;

	/**
	 * The table information_schema.SESSION_STATUS
	 */
	public static final SessionStatus SESSION_STATUS = com.mymock.db.information_schema.tables.SessionStatus.SESSION_STATUS;

	/**
	 * The table information_schema.SESSION_VARIABLES
	 */
	public static final SessionVariables SESSION_VARIABLES = com.mymock.db.information_schema.tables.SessionVariables.SESSION_VARIABLES;

	/**
	 * The table information_schema.STATISTICS
	 */
	public static final Statistics STATISTICS = com.mymock.db.information_schema.tables.Statistics.STATISTICS;

	/**
	 * The table information_schema.TABLES
	 */
	public static final com.mymock.db.information_schema.tables.Tables TABLES = com.mymock.db.information_schema.tables.Tables.TABLES;

	/**
	 * The table information_schema.TABLESPACES
	 */
	public static final Tablespaces TABLESPACES = com.mymock.db.information_schema.tables.Tablespaces.TABLESPACES;

	/**
	 * The table information_schema.TABLE_CONSTRAINTS
	 */
	public static final TableConstraints TABLE_CONSTRAINTS = com.mymock.db.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

	/**
	 * The table information_schema.TABLE_PRIVILEGES
	 */
	public static final TablePrivileges TABLE_PRIVILEGES = com.mymock.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table information_schema.TRIGGERS
	 */
	public static final Triggers TRIGGERS = com.mymock.db.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table information_schema.USER_PRIVILEGES
	 */
	public static final UserPrivileges USER_PRIVILEGES = com.mymock.db.information_schema.tables.UserPrivileges.USER_PRIVILEGES;

	/**
	 * The table information_schema.VIEWS
	 */
	public static final Views VIEWS = com.mymock.db.information_schema.tables.Views.VIEWS;
}
