CREATE TABLE URL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ADDRESS CHAR DEFAULT NULL,
  TS TIMESTAMP,
  NUM INT DEFAULT 0,
  Constraint unique_url UNIQUE(ADDRESS)
);

CREATE TABLE HEADER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  URL_ID INT,
  HEADER_NAME CHAR(30),
  HEADER_VALUE CHAR(255),
  Constraint fk_header_url FOREIGN KEY(URL_ID) REFERENCES URL(ID) ON DELETE CASCADE
)
