/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.firstdb;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.firstdb.tables.Ctest;


/**
 * Convenience access to all tables in firstdb
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table firstdb.ctest
	 */
	public static final Ctest CTEST = org.jooq.example.gradle.db.firstdb.tables.Ctest.CTEST;
}
