/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_.tables.records;


import com.mymock.webproxy.db.public_.tables.Wpurl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WpurlRecord extends UpdatableRecordImpl<WpurlRecord> implements Record5<Integer, String, Timestamp, Integer, byte[]> {

	private static final long serialVersionUID = 918364855;

	/**
	 * Setter for <code>PUBLIC.WPURL.ID</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.WPURL.ID</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.WPURL.ADDRESS</code>.
	 */
	public void setAddress(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.WPURL.ADDRESS</code>.
	 */
	public String getAddress() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.WPURL.TS</code>.
	 */
	public void setTs(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.WPURL.TS</code>.
	 */
	public Timestamp getTs() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.WPURL.CNT</code>.
	 */
	public void setCnt(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.WPURL.CNT</code>.
	 */
	public Integer getCnt() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.WPURL.CONTENT</code>.
	 */
	public void setContent(byte[] value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.WPURL.CONTENT</code>.
	 */
	public byte[] getContent() {
		return (byte[]) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, Integer, byte[]> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, Integer, byte[]> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Wpurl.WPURL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Wpurl.WPURL.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Wpurl.WPURL.TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Wpurl.WPURL.CNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field5() {
		return Wpurl.WPURL.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getCnt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value5() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord value2(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord value3(Timestamp value) {
		setTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord value4(Integer value) {
		setCnt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord value5(byte[] value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WpurlRecord values(Integer value1, String value2, Timestamp value3, Integer value4, byte[] value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WpurlRecord
	 */
	public WpurlRecord() {
		super(Wpurl.WPURL);
	}

	/**
	 * Create a detached, initialised WpurlRecord
	 */
	public WpurlRecord(Integer id, String address, Timestamp ts, Integer cnt, byte[] content) {
		super(Wpurl.WPURL);

		setValue(0, id);
		setValue(1, address);
		setValue(2, ts);
		setValue(3, cnt);
		setValue(4, content);
	}
}
