/**
 * This class is generated by jOOQ
 */
package com.mymock.db.firstdb;


import com.mymock.db.firstdb.tables.Ctest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Firstdb extends SchemaImpl {

	private static final long serialVersionUID = -23938449;

	/**
	 * The reference instance of <code>firstdb</code>
	 */
	public static final Firstdb FIRSTDB = new Firstdb();

	/**
	 * No further instances allowed
	 */
	private Firstdb() {
		super("firstdb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Ctest.CTEST);
	}
}
