/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import com.mymock.webproxy.db.public_.tables.Header;
import com.mymock.webproxy.db.public_.tables.SchemaVersion;
import com.mymock.webproxy.db.public_.tables.Url;
import com.mymock.webproxy.db.public_.tables.records.HeaderRecord;
import com.mymock.webproxy.db.public_.tables.records.SchemaVersionRecord;
import com.mymock.webproxy.db.public_.tables.records.UrlRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<UrlRecord, Integer> IDENTITY_URL = Identities0.IDENTITY_URL;
	public static final Identity<HeaderRecord, Integer> IDENTITY_HEADER = Identities0.IDENTITY_HEADER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;
	public static final UniqueKey<UrlRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
	public static final UniqueKey<UrlRecord> UNIQUE_URL = UniqueKeys0.UNIQUE_URL;
	public static final UniqueKey<HeaderRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<HeaderRecord, UrlRecord> FK_HEADER_URL = ForeignKeys0.FK_HEADER_URL;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<UrlRecord, Integer> IDENTITY_URL = createIdentity(Url.URL, Url.URL.ID);
		public static Identity<HeaderRecord, Integer> IDENTITY_HEADER = createIdentity(Header.HEADER, Header.HEADER.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = createUniqueKey(SchemaVersion.SCHEMA_VERSION, SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
		public static final UniqueKey<UrlRecord> CONSTRAINT_1 = createUniqueKey(Url.URL, Url.URL.ID);
		public static final UniqueKey<UrlRecord> UNIQUE_URL = createUniqueKey(Url.URL, Url.URL.ADDRESS);
		public static final UniqueKey<HeaderRecord> CONSTRAINT_7 = createUniqueKey(Header.HEADER, Header.HEADER.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<HeaderRecord, UrlRecord> FK_HEADER_URL = createForeignKey(com.mymock.webproxy.db.public_.Keys.CONSTRAINT_1, Header.HEADER, Header.HEADER.URL_ID);
	}
}
