/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import com.mymock.webproxy.db.public_.tables.SchemaVersion;
import com.mymock.webproxy.db.public_.tables.Wpheader;
import com.mymock.webproxy.db.public_.tables.Wpurl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = 1250115696;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_85E08B77_656E_441D_ADFB_DAB575AF520F,
			Sequences.SYSTEM_SEQUENCE_A56E76FB_D170_4E66_A7AD_9D4B6BDC245B);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			SchemaVersion.SCHEMA_VERSION,
			Wpurl.WPURL,
			Wpheader.WPHEADER);
	}
}
