/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_4BDFCB2C_244D_4C2D_ABFD_167F8C89C8E5</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_4BDFCB2C_244D_4C2D_ABFD_167F8C89C8E5 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_4BDFCB2C_244D_4C2D_ABFD_167F8C89C8E5", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_B5571BC1_E39A_4301_989C_0C702CC49666</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_B5571BC1_E39A_4301_989C_0C702CC49666 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_B5571BC1_E39A_4301_989C_0C702CC49666", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
