/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_829066C9_9692_409B_A411_C648C196EB7E</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_829066C9_9692_409B_A411_C648C196EB7E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_829066C9_9692_409B_A411_C648C196EB7E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_8E27C635_FA1D_4369_8C71_426B8EE6A599</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_8E27C635_FA1D_4369_8C71_426B8EE6A599 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_8E27C635_FA1D_4369_8C71_426B8EE6A599", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
