/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1D9903CE_6086_4809_A491_F5E6057FE4C2</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_1D9903CE_6086_4809_A491_F5E6057FE4C2 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1D9903CE_6086_4809_A491_F5E6057FE4C2", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_6A0D66E4_546D_4280_9EB4_520A07235145</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_6A0D66E4_546D_4280_9EB4_520A07235145 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_6A0D66E4_546D_4280_9EB4_520A07235145", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
