/**
 * This class is generated by jOOQ
 */
package com.mymock.webproxy.db.public_;


import com.mymock.webproxy.db.public_.tables.Header;
import com.mymock.webproxy.db.public_.tables.SchemaVersion;
import com.mymock.webproxy.db.public_.tables.Url;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = com.mymock.webproxy.db.public_.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table PUBLIC.URL
	 */
	public static final Url URL = com.mymock.webproxy.db.public_.tables.Url.URL;

	/**
	 * The table PUBLIC.HEADER
	 */
	public static final Header HEADER = com.mymock.webproxy.db.public_.tables.Header.HEADER;
}
