/**
 * This class is generated by jOOQ
 */
package com.mymock.db.sys;


import com.mymock.db.sys.tables.HostSummary;
import com.mymock.db.sys.tables.HostSummaryByFileIo;
import com.mymock.db.sys.tables.HostSummaryByFileIoType;
import com.mymock.db.sys.tables.HostSummaryByStages;
import com.mymock.db.sys.tables.HostSummaryByStatementLatency;
import com.mymock.db.sys.tables.HostSummaryByStatementType;
import com.mymock.db.sys.tables.InnodbBufferStatsBySchema;
import com.mymock.db.sys.tables.InnodbBufferStatsByTable;
import com.mymock.db.sys.tables.InnodbLockWaits;
import com.mymock.db.sys.tables.IoByThreadByLatency;
import com.mymock.db.sys.tables.IoGlobalByFileByBytes;
import com.mymock.db.sys.tables.IoGlobalByFileByLatency;
import com.mymock.db.sys.tables.IoGlobalByWaitByBytes;
import com.mymock.db.sys.tables.IoGlobalByWaitByLatency;
import com.mymock.db.sys.tables.LatestFileIo;
import com.mymock.db.sys.tables.MemoryByHostByCurrentBytes;
import com.mymock.db.sys.tables.MemoryByThreadByCurrentBytes;
import com.mymock.db.sys.tables.MemoryByUserByCurrentBytes;
import com.mymock.db.sys.tables.MemoryGlobalByCurrentBytes;
import com.mymock.db.sys.tables.MemoryGlobalTotal;
import com.mymock.db.sys.tables.Metrics;
import com.mymock.db.sys.tables.Processlist;
import com.mymock.db.sys.tables.PsCheckLostInstrumentation;
import com.mymock.db.sys.tables.SchemaAutoIncrementColumns;
import com.mymock.db.sys.tables.SchemaIndexStatistics;
import com.mymock.db.sys.tables.SchemaObjectOverview;
import com.mymock.db.sys.tables.SchemaRedundantIndexes;
import com.mymock.db.sys.tables.SchemaTableLockWaits;
import com.mymock.db.sys.tables.SchemaTableStatistics;
import com.mymock.db.sys.tables.SchemaTableStatisticsWithBuffer;
import com.mymock.db.sys.tables.SchemaTablesWithFullTableScans;
import com.mymock.db.sys.tables.SchemaUnusedIndexes;
import com.mymock.db.sys.tables.Session;
import com.mymock.db.sys.tables.SessionSslStatus;
import com.mymock.db.sys.tables.StatementAnalysis;
import com.mymock.db.sys.tables.StatementsWithErrorsOrWarnings;
import com.mymock.db.sys.tables.StatementsWithFullTableScans;
import com.mymock.db.sys.tables.StatementsWithRuntimesIn_95thPercentile;
import com.mymock.db.sys.tables.StatementsWithSorting;
import com.mymock.db.sys.tables.StatementsWithTempTables;
import com.mymock.db.sys.tables.SysConfig;
import com.mymock.db.sys.tables.UserSummary;
import com.mymock.db.sys.tables.UserSummaryByFileIo;
import com.mymock.db.sys.tables.UserSummaryByFileIoType;
import com.mymock.db.sys.tables.UserSummaryByStages;
import com.mymock.db.sys.tables.UserSummaryByStatementLatency;
import com.mymock.db.sys.tables.UserSummaryByStatementType;
import com.mymock.db.sys.tables.Version;
import com.mymock.db.sys.tables.WaitClassesGlobalByAvgLatency;
import com.mymock.db.sys.tables.WaitClassesGlobalByLatency;
import com.mymock.db.sys.tables.WaitsByHostByLatency;
import com.mymock.db.sys.tables.WaitsByUserByLatency;
import com.mymock.db.sys.tables.WaitsGlobalByLatency;
import com.mymock.db.sys.tables.X$hostSummary;
import com.mymock.db.sys.tables.X$hostSummaryByFileIo;
import com.mymock.db.sys.tables.X$hostSummaryByFileIoType;
import com.mymock.db.sys.tables.X$hostSummaryByStages;
import com.mymock.db.sys.tables.X$hostSummaryByStatementLatency;
import com.mymock.db.sys.tables.X$hostSummaryByStatementType;
import com.mymock.db.sys.tables.X$innodbBufferStatsBySchema;
import com.mymock.db.sys.tables.X$innodbBufferStatsByTable;
import com.mymock.db.sys.tables.X$innodbLockWaits;
import com.mymock.db.sys.tables.X$ioByThreadByLatency;
import com.mymock.db.sys.tables.X$ioGlobalByFileByBytes;
import com.mymock.db.sys.tables.X$ioGlobalByFileByLatency;
import com.mymock.db.sys.tables.X$ioGlobalByWaitByBytes;
import com.mymock.db.sys.tables.X$ioGlobalByWaitByLatency;
import com.mymock.db.sys.tables.X$latestFileIo;
import com.mymock.db.sys.tables.X$memoryByHostByCurrentBytes;
import com.mymock.db.sys.tables.X$memoryByThreadByCurrentBytes;
import com.mymock.db.sys.tables.X$memoryByUserByCurrentBytes;
import com.mymock.db.sys.tables.X$memoryGlobalByCurrentBytes;
import com.mymock.db.sys.tables.X$memoryGlobalTotal;
import com.mymock.db.sys.tables.X$processlist;
import com.mymock.db.sys.tables.X$psDigestAvgLatencyDistribution;
import com.mymock.db.sys.tables.X$psDigest_95thPercentileByAvgUs;
import com.mymock.db.sys.tables.X$psSchemaTableStatisticsIo;
import com.mymock.db.sys.tables.X$schemaFlattenedKeys;
import com.mymock.db.sys.tables.X$schemaIndexStatistics;
import com.mymock.db.sys.tables.X$schemaTableLockWaits;
import com.mymock.db.sys.tables.X$schemaTableStatistics;
import com.mymock.db.sys.tables.X$schemaTableStatisticsWithBuffer;
import com.mymock.db.sys.tables.X$schemaTablesWithFullTableScans;
import com.mymock.db.sys.tables.X$session;
import com.mymock.db.sys.tables.X$statementAnalysis;
import com.mymock.db.sys.tables.X$statementsWithErrorsOrWarnings;
import com.mymock.db.sys.tables.X$statementsWithFullTableScans;
import com.mymock.db.sys.tables.X$statementsWithRuntimesIn_95thPercentile;
import com.mymock.db.sys.tables.X$statementsWithSorting;
import com.mymock.db.sys.tables.X$statementsWithTempTables;
import com.mymock.db.sys.tables.X$userSummary;
import com.mymock.db.sys.tables.X$userSummaryByFileIo;
import com.mymock.db.sys.tables.X$userSummaryByFileIoType;
import com.mymock.db.sys.tables.X$userSummaryByStages;
import com.mymock.db.sys.tables.X$userSummaryByStatementLatency;
import com.mymock.db.sys.tables.X$userSummaryByStatementType;
import com.mymock.db.sys.tables.X$waitClassesGlobalByAvgLatency;
import com.mymock.db.sys.tables.X$waitClassesGlobalByLatency;
import com.mymock.db.sys.tables.X$waitsByHostByLatency;
import com.mymock.db.sys.tables.X$waitsByUserByLatency;
import com.mymock.db.sys.tables.X$waitsGlobalByLatency;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sys extends SchemaImpl {

	private static final long serialVersionUID = -1371993530;

	/**
	 * The reference instance of <code>sys</code>
	 */
	public static final Sys SYS = new Sys();

	/**
	 * No further instances allowed
	 */
	private Sys() {
		super("sys");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			HostSummary.HOST_SUMMARY,
			HostSummaryByFileIo.HOST_SUMMARY_BY_FILE_IO,
			HostSummaryByFileIoType.HOST_SUMMARY_BY_FILE_IO_TYPE,
			HostSummaryByStages.HOST_SUMMARY_BY_STAGES,
			HostSummaryByStatementLatency.HOST_SUMMARY_BY_STATEMENT_LATENCY,
			HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE,
			InnodbBufferStatsBySchema.INNODB_BUFFER_STATS_BY_SCHEMA,
			InnodbBufferStatsByTable.INNODB_BUFFER_STATS_BY_TABLE,
			InnodbLockWaits.INNODB_LOCK_WAITS,
			IoByThreadByLatency.IO_BY_THREAD_BY_LATENCY,
			IoGlobalByFileByBytes.IO_GLOBAL_BY_FILE_BY_BYTES,
			IoGlobalByFileByLatency.IO_GLOBAL_BY_FILE_BY_LATENCY,
			IoGlobalByWaitByBytes.IO_GLOBAL_BY_WAIT_BY_BYTES,
			IoGlobalByWaitByLatency.IO_GLOBAL_BY_WAIT_BY_LATENCY,
			LatestFileIo.LATEST_FILE_IO,
			MemoryByHostByCurrentBytes.MEMORY_BY_HOST_BY_CURRENT_BYTES,
			MemoryByThreadByCurrentBytes.MEMORY_BY_THREAD_BY_CURRENT_BYTES,
			MemoryByUserByCurrentBytes.MEMORY_BY_USER_BY_CURRENT_BYTES,
			MemoryGlobalByCurrentBytes.MEMORY_GLOBAL_BY_CURRENT_BYTES,
			MemoryGlobalTotal.MEMORY_GLOBAL_TOTAL,
			Metrics.METRICS,
			Processlist.PROCESSLIST,
			PsCheckLostInstrumentation.PS_CHECK_LOST_INSTRUMENTATION,
			SchemaAutoIncrementColumns.SCHEMA_AUTO_INCREMENT_COLUMNS,
			SchemaIndexStatistics.SCHEMA_INDEX_STATISTICS,
			SchemaObjectOverview.SCHEMA_OBJECT_OVERVIEW,
			SchemaRedundantIndexes.SCHEMA_REDUNDANT_INDEXES,
			SchemaTablesWithFullTableScans.SCHEMA_TABLES_WITH_FULL_TABLE_SCANS,
			SchemaTableLockWaits.SCHEMA_TABLE_LOCK_WAITS,
			SchemaTableStatistics.SCHEMA_TABLE_STATISTICS,
			SchemaTableStatisticsWithBuffer.SCHEMA_TABLE_STATISTICS_WITH_BUFFER,
			SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES,
			Session.SESSION,
			SessionSslStatus.SESSION_SSL_STATUS,
			StatementsWithErrorsOrWarnings.STATEMENTS_WITH_ERRORS_OR_WARNINGS,
			StatementsWithFullTableScans.STATEMENTS_WITH_FULL_TABLE_SCANS,
			StatementsWithRuntimesIn_95thPercentile.STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE,
			StatementsWithSorting.STATEMENTS_WITH_SORTING,
			StatementsWithTempTables.STATEMENTS_WITH_TEMP_TABLES,
			StatementAnalysis.STATEMENT_ANALYSIS,
			SysConfig.SYS_CONFIG,
			UserSummary.USER_SUMMARY,
			UserSummaryByFileIo.USER_SUMMARY_BY_FILE_IO,
			UserSummaryByFileIoType.USER_SUMMARY_BY_FILE_IO_TYPE,
			UserSummaryByStages.USER_SUMMARY_BY_STAGES,
			UserSummaryByStatementLatency.USER_SUMMARY_BY_STATEMENT_LATENCY,
			UserSummaryByStatementType.USER_SUMMARY_BY_STATEMENT_TYPE,
			Version.VERSION,
			WaitsByHostByLatency.WAITS_BY_HOST_BY_LATENCY,
			WaitsByUserByLatency.WAITS_BY_USER_BY_LATENCY,
			WaitsGlobalByLatency.WAITS_GLOBAL_BY_LATENCY,
			WaitClassesGlobalByAvgLatency.WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY,
			WaitClassesGlobalByLatency.WAIT_CLASSES_GLOBAL_BY_LATENCY,
			X$hostSummary.X$HOST_SUMMARY,
			X$hostSummaryByFileIo.X$HOST_SUMMARY_BY_FILE_IO,
			X$hostSummaryByFileIoType.X$HOST_SUMMARY_BY_FILE_IO_TYPE,
			X$hostSummaryByStages.X$HOST_SUMMARY_BY_STAGES,
			X$hostSummaryByStatementLatency.X$HOST_SUMMARY_BY_STATEMENT_LATENCY,
			X$hostSummaryByStatementType.X$HOST_SUMMARY_BY_STATEMENT_TYPE,
			X$innodbBufferStatsBySchema.X$INNODB_BUFFER_STATS_BY_SCHEMA,
			X$innodbBufferStatsByTable.X$INNODB_BUFFER_STATS_BY_TABLE,
			X$innodbLockWaits.X$INNODB_LOCK_WAITS,
			X$ioByThreadByLatency.X$IO_BY_THREAD_BY_LATENCY,
			X$ioGlobalByFileByBytes.X$IO_GLOBAL_BY_FILE_BY_BYTES,
			X$ioGlobalByFileByLatency.X$IO_GLOBAL_BY_FILE_BY_LATENCY,
			X$ioGlobalByWaitByBytes.X$IO_GLOBAL_BY_WAIT_BY_BYTES,
			X$ioGlobalByWaitByLatency.X$IO_GLOBAL_BY_WAIT_BY_LATENCY,
			X$latestFileIo.X$LATEST_FILE_IO,
			X$memoryByHostByCurrentBytes.X$MEMORY_BY_HOST_BY_CURRENT_BYTES,
			X$memoryByThreadByCurrentBytes.X$MEMORY_BY_THREAD_BY_CURRENT_BYTES,
			X$memoryByUserByCurrentBytes.X$MEMORY_BY_USER_BY_CURRENT_BYTES,
			X$memoryGlobalByCurrentBytes.X$MEMORY_GLOBAL_BY_CURRENT_BYTES,
			X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL,
			X$processlist.X$PROCESSLIST,
			X$psDigest_95thPercentileByAvgUs.X$PS_DIGEST_95TH_PERCENTILE_BY_AVG_US,
			X$psDigestAvgLatencyDistribution.X$PS_DIGEST_AVG_LATENCY_DISTRIBUTION,
			X$psSchemaTableStatisticsIo.X$PS_SCHEMA_TABLE_STATISTICS_IO,
			X$schemaFlattenedKeys.X$SCHEMA_FLATTENED_KEYS,
			X$schemaIndexStatistics.X$SCHEMA_INDEX_STATISTICS,
			X$schemaTablesWithFullTableScans.X$SCHEMA_TABLES_WITH_FULL_TABLE_SCANS,
			X$schemaTableLockWaits.X$SCHEMA_TABLE_LOCK_WAITS,
			X$schemaTableStatistics.X$SCHEMA_TABLE_STATISTICS,
			X$schemaTableStatisticsWithBuffer.X$SCHEMA_TABLE_STATISTICS_WITH_BUFFER,
			X$session.X$SESSION,
			X$statementsWithErrorsOrWarnings.X$STATEMENTS_WITH_ERRORS_OR_WARNINGS,
			X$statementsWithFullTableScans.X$STATEMENTS_WITH_FULL_TABLE_SCANS,
			X$statementsWithRuntimesIn_95thPercentile.X$STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE,
			X$statementsWithSorting.X$STATEMENTS_WITH_SORTING,
			X$statementsWithTempTables.X$STATEMENTS_WITH_TEMP_TABLES,
			X$statementAnalysis.X$STATEMENT_ANALYSIS,
			X$userSummary.X$USER_SUMMARY,
			X$userSummaryByFileIo.X$USER_SUMMARY_BY_FILE_IO,
			X$userSummaryByFileIoType.X$USER_SUMMARY_BY_FILE_IO_TYPE,
			X$userSummaryByStages.X$USER_SUMMARY_BY_STAGES,
			X$userSummaryByStatementLatency.X$USER_SUMMARY_BY_STATEMENT_LATENCY,
			X$userSummaryByStatementType.X$USER_SUMMARY_BY_STATEMENT_TYPE,
			X$waitsByHostByLatency.X$WAITS_BY_HOST_BY_LATENCY,
			X$waitsByUserByLatency.X$WAITS_BY_USER_BY_LATENCY,
			X$waitsGlobalByLatency.X$WAITS_GLOBAL_BY_LATENCY,
			X$waitClassesGlobalByAvgLatency.X$WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY,
			X$waitClassesGlobalByLatency.X$WAIT_CLASSES_GLOBAL_BY_LATENCY);
	}
}
