/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.sys.routines;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.sys.Sys;
import org.jooq.impl.AbstractRoutine;


/**
 * 
 *  Description
 *  
 *  Enable all background thread instrumentation within Performance Schema.
 *  
 *  Parameters
 *  
 *  None.
 *  
 *  Example
 *  
 *  mysql> CALL sys.ps_setup_enable_background_threads();
 *  +-------------------------------+
 *  | summary                       |
 *  +-------------------------------+
 *  | Enabled 18 background threads |
 *  +-------------------------------+
 *  1 row in set (0.00 sec)
 *  
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsSetupEnableBackgroundThreads extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1427528960;

	/**
	 * Create a new routine call instance
	 */
	public PsSetupEnableBackgroundThreads() {
		super("ps_setup_enable_background_threads", Sys.SYS);
	}
}
